repos:
  # 1. BLACK HOOK
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        args: [--line-length=100]

  # 2. ISORT HOOK
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # 3. MYPY HOOK (Allow failures)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-python-dateutil
        args:
          - --ignore-missing-imports
          - --disable-error-code=dict-item
          - --disable-error-code=attr-defined
        verbose: true

  # 4. PYLINT HOOK (Allow failures)
  - repo: https://github.com/pycqa/pylint
    rev: v4.0.4
    hooks:
      - id: pylint
        args: [--rcfile=backend/.pylintrc]
        # Don't fail commit on pylint warnings
        verbose: true
        # Only fail on errors, not warnings
        args: [--rcfile=backend/.pylintrc, --errors-only]