[tool.black]
line-length = 100  # Increased from 88 to 100
target-version = ['py312']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100  # Increased from 88 to 100
multi_line_output = 3
ensure_newline_before_comments = true 
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
# Add these to be more lenient
disable_error_code = ["dict-item", "attr-defined"]

[tool.pylint.messages_control]
disable = [
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
    "R0903",  # too-few-public-methods
    "E0401",  # import-error
    "C0301",  # line-too-long
    "R0911",  # too-many-return-statements
    "R1705",  # no-else-return
    "W0718",  # broad-exception-caught
    "W0621",  # redefined-outer-name
    "W0613",  # unused-argument
    "R0914",  # too-many-locals
    "W0707",  # raise-missing-from
    "E0611",  # no-name-in-module
]

[tool.pylint.format]
max-line-length = 100  # Increased from 88 to 100